### ISSUE TITLE
Allow for customizing browser in which maps open beyond default action

### ISSUE THREAD

**Issue by rootwork** [stuartcryan/advanced-google-maps-alfred-workflow#3]
Other than the `maps` action, which uses Alfred's native "Open URL" function and thus can be set to open in a non-default browser, the other actions all point to Perl scripts, which don't allow you to change what browser they open in -- they just open in the default browser.

It'd be nice to make that configurable.

In the meantime, do you happen to know how to edit the Perl scripts to specify a particular program in which the URLs should open?

Thanks -- and thanks for this great workflow!

**Comment by stuartcryan** [comment]
That is actually completely valid. This dates back to when there were limited ways to structure flows as you had one input, one process and one output. The problem here was that I could not put together a process with an output opening in the native Alfred browser output.

At least, that is what is foremost in my mind. 

So with that in mind, how does this beta work for you?
https://dl.dropboxusercontent.com/u/9093155/Advanced%20Google%20Maps%20Search%201.2.0beta.alfredworkflow

Managed to mock it up over 15 minutes at lunch. Also I have added a Workflow Environment Variable.

It is quite rudimentary at the moment, but in essence if you (for example) set the variable to the domain for your locale. For example 'com.au' it will use google.com.au if you use 'com.tw' it will use google.com.tw.

Please have a play and let me know how you go and I will prep a proper release.

**Comment by stuartcryan** [comment]
This has now been pushed in V1.3.0 release.
