### ISSUE TITLE
Adding additional 'locations' (aside from 'home' and 'work')

### ISSUE THREAD

**Issue by wiffleman** [stuartcryan/advanced-google-maps-alfred-workflow#4]
Hi Stuart, 

Great workflow- just wondering if it is still in development?

Couple questions: 

1. where is the 'mapsethome' variable stored within Alfred?
2. any way to add additional set-word locations? i.e. gym, names of others' locations etc?

Thanks!

**Comment by stuartcryan** [comment]
Hi @eggplantsplz,
It is, though it has been an immensely busy year this year. I am spending some time on this at the moment and have an alpha version in release available as per my recent tweet --> https://twitter.com/StuartCRyan/status/944817743353675776 .

The mapsethome is stored in Apple's Keychain, not the best place for it by any measure, but it goes back to well before Alfred had any variables or parameters on the workflows itself.

I am pondering how this would best work. Given what you know about how things are invoked today, how would you anticipate it would work (and I mean this step by step).

Also, if you could have a look at the new version, as it has some additional modifiers which may change how you would need to think about the solution working.

I look forward to your thoughts, and sincerely apologise for the delay.
Stuart

**Comment by stuartcryan** [comment]
Also @eggplantsplz, I have had a look and at this time, doing dynamic locations. At least, not fully featured like I have with 'work' and 'home'.

I could add in some custom locations that work by typing 'dir <different location name>. However, I would not be able to dynamically load them into their own keyword mechanisms (such as 'dirfh' 'dirth' 'dirfw' etc).

So, can you tell me more about exactly how you would want to be using them? The options are quite limited at the moment, but I would like to see if I can come up with a good feature idea to submit, but would like to know what sort of custom ones other than gym you might make, and your expectations around whether they would work just within the 'dir' scope, or needing to have their own 'dirfh' etc.

Look forward to hearing from you.

**Comment by wiffleman** [comment]
Hey @stuartcryan ! Sorry for the delay in getting back to you. I have admittedly been neglecting some of these emails!

In terms of custom locations, I envisioned something like "dir home to gym" or "dir school to gym" something along those lines, and having pre-defined addresses for "gym" and "school" similar to the way that "home" is defined using 'mapsethome'.

Not sure if this is more clear in terms of my pathway for use, but it has been a very helpful workflow nonetheless so I applaud you for your work!

**Comment by stuartcryan** [comment]
@eggplantsplz no worries at all, I know I was sending out quite a few emails over the Chrissy break, I wanted to get in to a bit of coding and even though I just released v 1.3.1, v2.0.0 is nearing completion, I am just wanting to see if there is anything I can do with this first. 

Hmm so if I provided the custom address just for the dir command that could work.

What I might be able to achieve is this:
What it would do:

- for dir command let you specify custom options that would be translated from 'gym' and 'school' and 'whateveryouwanted' to the associated address.
- for the dirfh/dirfw command you could say dirfw gym, dirfh gym as an example or dirfw school?.

What it wouldn't do:

-It wouldn't give you dirfg dirtg (i.e. the quick access shortcuts, because I can't dynamically add them).

Would that kinda do what you are looking for? It is at least the biggest leap forward I can programatically achieve within the current features of Alfred?

Let me know and I can have a tinker before releasing 2.0.0.

**Comment by stuartcryan** [comment]
OK haha I couldn't resist... have a nice little squiz at a pressie that I have for you: https://web.tresorit.com/l#mLmeguAU8RSyMAbNy4I2Bw details of how to do this are on the Workflow Readme Page.

The long and short is:
In the customLocations Alfred Workflow Environment Variable page put something like this:

('gym:49 Queens Rd, Five Dock NSW 2046','school:1A Harris Rd, Five Dock NSW 2046','dc:26 Cabarita Rd, Concord NSW 2137','bwood:100 Burwood Rd, Burwood NSW 2134','csturt:Charles Sturt University Panorama Avenue BATHURST NSW','po:48 Majors Bay Rd, Concord NSW 2137')

This will let you use any of the custom location names in any of the existing commands. As mentioned, due to the way Alfred works at the moment, I am unable to dynamically add additional 'dirfg' or 'dirtg' commands for to and from the gym as an example.

Hopefully this covers off 99% of what you wanted to achieve?

**Comment by stuartcryan** [comment]
ALL RIGHTY! This has been completed and is ready to roll. V2.0.0 Release IMPENDING!!!

(I highly recommend as soon as I do a read of the README page :D #coolNewThingsInbound, though if you just switch to the develop branch you can see it all now!)
